### ISSUE TITLE
Invoke-SpfDkimDmarc  with -File <filename> as source returns the last entry twice.

### ISSUE THREAD

**Issue by pacal683** [T13nn3s/Invoke-SpfDkimDmarc#24]
Using a source file with the following entries:
feistweiller.com
feistweiller.org

does not matter if last line is blank or not.  

gives this output:
PS C: > Invoke-SpfDkimDmarc -File .\domainlist.txt

Name          : feistweiller.com
SpfRecord     :
SpfAdvisory   : Domain does not have an SPF record. To prevent abuse of this domain, please add an SPF record to it.
DmarcRecord   :
DmarcAdvisory : Does not have a DMARC record. This domain is at risk to being abused by phishers and spammers.
DkimRecord    :
DkimSelector  : dkim
DkimAdvisory  : We couldn't find a DKIM record associated with your domain.

Name          : feistweiller.org
SpfRecord     :
SpfAdvisory   : Domain does not have an SPF record. To prevent abuse of this domain, please add an SPF record to it.
DmarcRecord   :
DmarcAdvisory : Does not have a DMARC record. This domain is at risk to being abused by phishers and spammers.
DkimRecord    :
DkimSelector  : dkim
DkimAdvisory  : We couldn't find a DKIM record associated with your domain.

Name          : feistweiller.org
SpfRecord     :
SpfAdvisory   : Domain does not have an SPF record. To prevent abuse of this domain, please add an SPF record to it.
DmarcRecord   :
DmarcAdvisory : Does not have a DMARC record. This domain is at risk to being abused by phishers and spammers.
DkimRecord    :
DkimSelector  : dkim
DkimAdvisory  : We couldn't find a DKIM record associated with your domain.

**Comment by T13nn3s** [comment]
Hi @pacal683, 

I checked your issue and I can confirm this bug. I'm checking the module and will fix this bug and update the script.

**Comment by T13nn3s** [comment]
Fixed in version 1.5.2
