### ISSUE TITLE
Invoke-SpfDkimDmarc not using -server property

### ISSUE THREAD

**Issue by tomdhoore-houseofhr** [T13nn3s/Invoke-SpfDkimDmarc#32]
Hi, when using the Invoke-SpfDkimDmarc , it seems like the -server parameter is not being used (due to split dns, the invoke-command seems to use the local dns server, eg the get-spfrecord uses the actual external dns server (domain name changed to not disclose too much info)

PS C:\Users\username> invoke-spfdkimdmarc -name hxx.com -server 1.1.1.1

Name          : hxx.com
SpfRecord     :
SpfAdvisory   : Domain does not have an SPF record. To prevent abuse of this domain, please add an SPF record to it.
DmarcRecord   :
DmarcAdvisory : Does not have a DMARC record. This domain is at risk to being abused by phishers and spammers.
DkimRecord    :
DkimSelector  : dkim
DkimAdvisory  : We couldn't find a DKIM record associated with your domain.

PS C:\Users\username> get-spfrecord -name hxx.com -server 1.1.1.1

Name          SPFRecord                                                                                                                                                           SPFAdvisory
----          ---------                                                                                                                                                           -----------
hxx.com v=spf1 a include:spf.protection.outlook.com <cut> -all An SPF-record is configured and the policy is sufficiently strict.

**Comment by T13nn3s** [comment]
This will be fixed in the next release.
