### ISSUE TITLE
"Domain has more than one SPF-record." bug

### ISSUE THREAD

**Issue by grumblebum73** [T13nn3s/Invoke-SpfDkimDmarc#33]
If an SPF has a redirect in the actual record, and then that has an include, that has another include, and so on... the code provides the following erroneous advisory...

"Domain has more than one SPF-record. One SPF record for one domain. This is explicitly defined in RFC4408"

The SPF for mimecast.com is an example of this record construct, and is a legitimate record.

**Comment by T13nn3s** [comment]
This will be fixed in the next release.
