### ISSUE TITLE
Domain does not have an SPF record

### ISSUE THREAD

**Issue by Murray-Harris** [T13nn3s/Invoke-SpfDkimDmarc#34]
when i query my domain i am told that a SPF record does not exist when it does.
![image](https://user-images.githubusercontent.com/125328664/218619491-ba4b83aa-3914-416d-bdbd-f00c57bdb28e.png)

**Comment by T13nn3s** [comment]
Hi @Murray-Harris,

Thanks for your question. Are you in a split DNS environment? If so, please use the `-Server` parameter with an external DNS Server to check the SPF-record.

**Comment by T13nn3s** [comment]
No response, issue closed.
