### ISSUE TITLE
DkimSelector not working for Invoke-SpfDkimDmarc

### ISSUE THREAD

**Issue by Rugby-Ball** [T13nn3s/Invoke-SpfDkimDmarc#37]
For `Invoke-SpfDkimDmarc`, it seems `-DkimSelector` is not working. No matter what you put, it defaults to `dkim` as the selector.

This is not the case for `Get-DKIMRecord`, which accepts the `-DkimSelector` used and returns expected results.

**Comment by T13nn3s** [comment]
Hi @Rugby-Ball,

I am going to test it and if I actually find that this issue is present it will be fixed in the next release.
