### ISSUE TITLE
Requested Update to Readme/help docs

### ISSUE THREAD

**Issue by usmcgeek** [T13nn3s/Invoke-SpfDkimDmarc#40]
Simple update for those of us checking multiple domains using the -File switch.  I used a source CSV file with the domains on a row each.

running the "invoke-spfdkimdmarc" with "-file C:\path\to\file.csv" and "| export-csv -Path C:\path\to\export.csv -NoTypeInformation" works perfectly.

Wanted to note this as it is super helpful.

**Comment by T13nn3s** [comment]
Thanks! I will update the help files with these information
